--------------------------------------------------------
--  File created - Tuesday-April-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOMAINE
--------------------------------------------------------

  CREATE TABLE "HR"."DOMAINE" 
   (	"ID_DOMAINE" NUMBER(*,0), 
	"NOM_DOMAINE" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDITION_LIVRE
--------------------------------------------------------

  CREATE TABLE "HR"."EDITION_LIVRE" 
   (	"ISBN" NUMBER(*,0), 
	"ANNEE_PUBLICATION" NUMBER(*,0), 
	"EDITEUR" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES_ORACLE
--------------------------------------------------------

  CREATE TABLE "HR"."EMPLOYES_ORACLE" 
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"NOM_EMPLOYE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PRENOM_EMPLOYE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"NOMBRE_EMPRUNT" NUMBER(*,0), 
	"ID_EMPRUNT" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPRUNT
--------------------------------------------------------

  CREATE TABLE "HR"."EMPRUNT" 
   (	"ID_EMPRUNT" NUMBER(*,0), 
	"DATE_EMPRUNT" DATE, 
	"DATE_RETOUR" DATE, 
	"ID_LIVRE" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIVRES
--------------------------------------------------------

  CREATE TABLE "HR"."LIVRES" 
   (	"ID_LIVRE" NUMBER(*,0), 
	"AUTEUR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TITRE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"NOMBRE_EXEMPLAIRE" NUMBER(*,0), 
	"ISBN" NUMBER(*,0), 
	"ID_SOUS_DOMAINE" NUMBER(*,0), 
	"ID_DOMAINE" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOUS_DOMAINE
--------------------------------------------------------

  CREATE TABLE "HR"."SOUS_DOMAINE" 
   (	"ID_SOUS_DOMAINE" NUMBER(*,0), 
	"NOM_SOUS_DOMAINE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_DOMAINE" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.DOMAINE
SET DEFINE OFF;
Insert into HR.DOMAINE (ID_DOMAINE,NOM_DOMAINE) values (1,'informatique');
Insert into HR.DOMAINE (ID_DOMAINE,NOM_DOMAINE) values (0,'Science-fiction');
Insert into HR.DOMAINE (ID_DOMAINE,NOM_DOMAINE) values (2,'Finance');
REM INSERTING into HR.EDITION_LIVRE
SET DEFINE OFF;
Insert into HR.EDITION_LIVRE (ISBN,ANNEE_PUBLICATION,EDITEUR) values (0,2007,'Gallimard');
Insert into HR.EDITION_LIVRE (ISBN,ANNEE_PUBLICATION,EDITEUR) values (1,2007,'Livre de poche');
REM INSERTING into HR.EMPLOYES_ORACLE
SET DEFINE OFF;
REM INSERTING into HR.EMPRUNT
SET DEFINE OFF;
REM INSERTING into HR.LIVRES
SET DEFINE OFF;
Insert into HR.LIVRES (ID_LIVRE,AUTEUR,TITRE,NOMBRE_EXEMPLAIRE,ISBN,ID_SOUS_DOMAINE,ID_DOMAINE) values (0,'J.K. Rowling','Harry Potter et Les Reliques de la mort Partie 1',10,1,0,0);
Insert into HR.LIVRES (ID_LIVRE,AUTEUR,TITRE,NOMBRE_EXEMPLAIRE,ISBN,ID_SOUS_DOMAINE,ID_DOMAINE) values (1,'Will Smith','Bad Boys 3',2,1,1,0);
REM INSERTING into HR.SOUS_DOMAINE
SET DEFINE OFF;
Insert into HR.SOUS_DOMAINE (ID_SOUS_DOMAINE,NOM_SOUS_DOMAINE,ID_DOMAINE) values (0,'Magie',0);
Insert into HR.SOUS_DOMAINE (ID_SOUS_DOMAINE,NOM_SOUS_DOMAINE,ID_DOMAINE) values (1,'Space Opera',0);
Insert into HR.SOUS_DOMAINE (ID_SOUS_DOMAINE,NOM_SOUS_DOMAINE,ID_DOMAINE) values (2,'Programmation',1);
Insert into HR.SOUS_DOMAINE (ID_SOUS_DOMAINE,NOM_SOUS_DOMAINE,ID_DOMAINE) values (3,'Base de données',1);
